#!/bin/bash

###############################################
#           Created by CyberMC-Tech           #
#   Github: https://github.com/CyberMC-Tech   #
###############################################

# Description:

# NOTE: THIS WILL NOT WORK ON DEBIAN BOOKWORM ONLY TRIXIE!!
# AstroNvim install script for debian testing "trixie" and ubuntu

###########################################################################################################
# Variables

PROGRAM="AstroNvim"

###########################################################################################################
# Listing commands for easy access

update_upgrade() {
    sudo apt update  && sudo apt upgrade -y
    install_depends
}

install_depends() {
    sudo apt install -y gdu git curl ripgrep &&
    curl -LO https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.deb
    sudo dpkg --force-overwrite --install ./nvim-linux64.deb 1> /dev/null
    rm nvim-linux64.deb
    curl -LO https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Linux_x86_64.tar.gz
    gunzip lazygit_0.40.2_Linux_x86_64.tar.gz && tar -xf lazygit_0.40.2_Linux_x86_64.tar
    sudo mv lazygit /usr/bin
    rm lazygit_0.40.2_Linux_x86_64.tar
    curl -LO https://github.com/ClementTsang/bottom/releases/download/0.9.6/bottom_0.9.6_amd64.deb
    sudo dpkg --force-overwrite --install bottom_0.9.6_amd64.deb 1>/dev/null
    rm bottom_0.9.6_amd64.deb
    delete_nvim
}

astronvim_setup() {
    git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
    success
}

############################################################################################################
# Ask the user if they want to install

confirm() {
    echo -e "\nYou are about to install ${1}."
    sleep 2
    echo -e "\nBe sure to backup your current nvim config first!"
    sleep 2
    echo -e "\nAre you ready to install?"
    sleep 2
    echo -en "\n[(Y)es|(n)o]: "
    read -r response
    check_ans "$response"
}

############################################################################################################
# Exit the script

abort() {
    echo -e "\nAborting installation...\n"
    sleep 2
    exit 0
}

############################################################################################################
# Rerun command until user answers Y or N

unknown_response() {
    echo -e "\nInvalid option\n"
    sleep 2
    echo -e "Please enter a vaild response\n"
    sleep 2
    confirm
}

############################################################################################################
# Moves the nvim folder to nvim.bak if it exists

delete_nvim() {
    rm -rf "$HOME/.config/nvim"
    rm -rf "$HOME/.local/share/nvim"
    astronvim_setup
}


############################################################################################################
# Error message if something fails

error() {
    echo -e "\nError: recieved a non-zero return code when running command \"${1}\""
    sleep 2
    echo -e "\nPlease check network connection and try again."
    sleep 2
    exit 1
}

#############################################################################################################
# Install script

install_program() {
    echo -e "\nBeginning Installation of ${PROGRAM}"
    update_upgrade
}

#############################################################################################################
# Check if user typed yes or no

check_ans() {
    ans=$(echo "${1::1}" | tr "[:upper:]" "[:lower:]")

    if [[ "$ans" == "y" ]] || [[ "$ans" == "" ]]; then
        install_program
    elif [[ "$ans" == "n" ]]; then
        abort
    else
        unknown_response
    fi
}

#############################################################################################################
# Lets user know install was successful

success() {
    echo -e "\n${PROGRAM} successfully installed\n\nYou can now start neovim by typing nvim.\n"
    sleep 2
    exit 0
}

#############################################################################################################
# main function for good practice and other possible uses

main() {
    confirm "${PROGRAM}"
}

#############################################################################################################
# Run call the main script

main
